# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
logging:
  level: INFO

imageDefaults:
  registry: docker.io
  namespace: odpi
  tag: latest
  pullPolicy: IfNotPresent

egeria:
  user: myuser
  cohort: coco
  server: myserver

connector:
  version: "2.10"
  url: "http://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=org.odpi.egeria&a=egeria-connector-hadoop-ecosystem-package&v=RELEASE&c=jar-with-dependencies"

image:
  egeria:
    name: egeria
    pullPolicy: IfNotPresent
  configure:
    name: egeria-configure
    pullPolicy: IfNotPresent
  apacheatlas:
    name: apache-atlas

apacheatlas:
  user: admin
  password: admin
  proxyserver: atlas

kafka:
  securityContext:
    enabled: false
  zookeeper:
    persistence:
      enabled: false
  persistence:
    enabled: false
